### ISSUE TITLE
Armor Isnt Showing up as armor

### ISSUE THREAD

**Issue by MommyLexie** [WispRecreationProject/WispSuperDiamonds#1]
![image](https://user-images.githubusercontent.com/81419755/112648911-a3b5df80-8e52-11eb-93fd-742b794d335f.png)
![image](https://user-images.githubusercontent.com/81419755/112648931-a87a9380-8e52-11eb-9306-35e879672513.png)

**Comment by YHDiamond** [comment]
fixed
